
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <ctype.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>

#define XHL_FILES_IMPL
#include "../Source/Third Party/xhl/xhl_files.h"

#define STB_SPRINTF_IMPLEMENTATION
#include "../Source/Third Party/stb/stb_sprintf.h"

#define max(a, b)  (((a) > (b)) ? (a) : (b))

void printUsage(int argc, char **argv)
{
  fprintf(stderr, "Cmd:");
  for (int i = 0; i < argc; i++)
    fprintf(stderr, "%s ", argv[i]);

  fprintf(stderr, "\nRecursive serialisation of files inside a directory\n"
    "Usage: %s /path/to/recursive/directory /path/to/serialisation/folder [file name]\n", argv[0]);
}

// every character needs a 1-to-1 replacement
void replaceWithValidCharacters(char *string, size_t size)
{
  if (!string)
    return;

  for (size_t i = 0; i < size; ++i)
    if (!isalnum(string[i]))
      string[i] = '_';
}

typedef struct rawData
{
  char *data;
  size_t size;
  size_t capacity;
} rawData;

void append(rawData *data, const char *format, ...)
{
  va_list args, copy;
  va_start(args, format);

  va_copy(copy, args);

  size_t newSize = stbsp_vsnprintf(NULL, 0, format, copy);

  if (newSize >= data->capacity - data->size)
  {
    data->capacity = max(newSize * 2, data->capacity * 2);
    data->data = (char *)realloc(data->data, data->capacity);
  }

  va_end(copy);

  data->size += stbsp_vsnprintf(data->data + data->size, (int)(data->capacity - data->size), format, args);

  va_end(args);
}

typedef struct DestinationFiles
{
  rawData headerData;
  rawData sourceData;
} DestinationFiles;

void fileCallback(void* data, const xfiles_list_item_t* item)
{
    const char* name = item->path + item->name_idx;
    if (strcmp(name, ".") == 0 || strcmp(name, "..") == 0)
      return;

    if (item->is_dir)
    {
      xfiles_list(item->path, data, fileCallback);
    }
    else
    {
      fprintf(stderr, "Entry: %s\n", item->path);

      unsigned char *fileData;
      size_t dataSize;
      xfiles_read(item->path, (void **)&fileData, &dataSize);

      size_t size = item->path_len - item->name_idx;
      char *string = (char *)malloc(1 + size);
      memcpy(string, item->path + item->name_idx, size);
      string[size] = '\0';
      replaceWithValidCharacters(string, size);

      DestinationFiles *files = (DestinationFiles *)data;

      append(&files->headerData,
        "\n\textern const unsigned char %.*s[];\n\tconstexpr unsigned long long %.*sSize = %zu;\n",
        (int)size, string, (int)size, string, dataSize);

      append(&files->sourceData, "\nconst unsigned char %.*s[] = {\n", (int)size, string);

      const size_t COL_WIDTH = 32;
      for (size_t i = 0, column = 0; i < dataSize; (++i), (++column))
      {
        const char *format = "%hhu,";
        if (column >= COL_WIDTH)
        {
          format = "\n%hhu,";
          column = 0;
        }
        append(&files->sourceData, format, fileData[i]);
      }

      append(&files->sourceData, "};\n\n");

      free(string);
      free(fileData);
    }
}

int main(int argc, char** argv)
{
  if (argc != 3)
  {
    printUsage(argc, argv);
    return 1;
  }

  const char *inputPath = argv[1];
  const char *outputPath = argv[2];
  const char *fileName = "BinaryData";

  if (argc >= 4)
    fileName = argv[3];

  DestinationFiles files = {0};

  append(&files.headerData, "// This file is auto-generated by %s. Do not edit!\n\n#pragma once\n\nnamespace %s\n{", argv[0], fileName);
  append(&files.sourceData, "// This file is auto-generated by %s. Do not edit!\n\n#include \"%s.hpp\"\n\nnamespace %s\n{", argv[0], fileName, fileName);

  xfiles_list(inputPath, &files, fileCallback);

  append(&files.headerData, "}\n");
  append(&files.sourceData, "\n}\n");

  xfiles_create_directory_recursive(outputPath);

  rawData headerPath = {0};
  rawData sourcePath = {0};

  append(&headerPath, "%s" XFILES_DIR_STR "%s.hpp", outputPath, fileName);
  append(&sourcePath, "%s" XFILES_DIR_STR "%s.cpp", outputPath, fileName);

  fprintf(stderr, "Generated header: %s\n", headerPath.data);
  fprintf(stderr, "Generated source: %s\n", sourcePath.data);

  xfiles_write(headerPath.data, files.headerData.data, files.headerData.size);
  xfiles_write(sourcePath.data, files.sourceData.data, files.sourceData.size);

  free(sourcePath.data);
  free(headerPath.data);
  free(files.sourceData.data);
  free(files.headerData.data);

  return 0;
}
